In [1]:
def dy_dx(x):
  return 2*x

In [2]:
dy_dx(2)

4

In [3]:
dy_dx(4)

8

In [4]:
import torch

x = torch.tensor(3.0, requires_grad=True)

In [5]:
x

tensor(3., requires_grad=True)

In [6]:
y = x**2

In [7]:
y

tensor(9., grad_fn=<PowBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor(6.)

In [10]:
import math

def dz_dx(x):
  return 2*x*math.cos(x**2)

In [11]:
dz_dx(5)

9.912028118634735

In [12]:
dz_dx(3)

-5.466781571308061

In [13]:
x = torch.tensor(3.0, requires_grad=True)

In [14]:
y = x**2
z = torch.sin(y)

In [15]:
y

tensor(9., grad_fn=<PowBackward0>)

In [16]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [17]:
x.grad

In [18]:
import torch.nn as nn

In [19]:
class Model(nn.Module):
  def __init__(self, new_features):
    super().__init__()
    self.linear = nn.Linear(new_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [20]:
data = torch.rand(10, 5)

In [21]:
data.shape

torch.Size([10, 5])

In [22]:
model = Model(data.shape[1])

In [23]:
model(data)

tensor([[0.4193],
        [0.4116],
        [0.4449],
        [0.4353],
        [0.4435],
        [0.4205],
        [0.4454],
        [0.4544],
        [0.4171],
        [0.4306]], grad_fn=<SigmoidBackward0>)

In [24]:
model.forward(data)

tensor([[0.4193],
        [0.4116],
        [0.4449],
        [0.4353],
        [0.4435],
        [0.4205],
        [0.4454],
        [0.4544],
        [0.4171],
        [0.4306]], grad_fn=<SigmoidBackward0>)

In [25]:
model.linear.weight

Parameter containing:
tensor([[-0.2371,  0.1679, -0.0100,  0.0113, -0.1410]], requires_grad=True)

In [26]:
model.linear.bias

Parameter containing:
tensor([-0.1712], requires_grad=True)

In [27]:
class Test:
  def __init__(self):
    print("from init")

  def __call__(self):
    print("from call")

  def testing(self):
    print("from testing")

In [28]:
obj = Test()

from init


In [29]:
obj.testing()

from testing


In [30]:
obj()

from call


# Model

In [31]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out


In [32]:
model = Model(data.shape[1])

In [33]:
model(data)

tensor([[0.5143],
        [0.5269],
        [0.5359],
        [0.5145],
        [0.5304],
        [0.5196],
        [0.5309],
        [0.5497],
        [0.5204],
        [0.5249]], grad_fn=<SigmoidBackward0>)

In [34]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2544,  0.1239, -0.2901, -0.1131,  0.1322],
        [-0.3482,  0.3713, -0.2964,  0.0932,  0.2540],
        [ 0.3977,  0.2351, -0.3482,  0.2150,  0.3911]], requires_grad=True)

In [35]:
model.linear2.weight

Parameter containing:
tensor([[-0.4537,  0.3103,  0.0172]], requires_grad=True)

In [36]:
model.linear1.bias

Parameter containing:
tensor([ 0.2997, -0.2435, -0.1691], requires_grad=True)

In [37]:
model.linear2.bias

Parameter containing:
tensor([0.2526], requires_grad=True)

# Sequential method

In [38]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [39]:
model = Model(data.shape[1])

In [40]:
model(data)

tensor([[0.3468],
        [0.4015],
        [0.3550],
        [0.3735],
        [0.3932],
        [0.3919],
        [0.3777],
        [0.3853],
        [0.3736],
        [0.3782]], grad_fn=<SigmoidBackward0>)

In [41]:
!pip install torchinfo

In [42]:
from torchinfo import summary

In [43]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 22
Trainable params: 22
Non-trainable params: 0

# Model Training

In [44]:
import pandas as pd

In [45]:
data = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [46]:
data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [48]:
data.shape

(569, 33)

In [49]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [50]:
data = data.drop(['id', 'Unnamed: 32'], axis=1)

In [51]:
data.shape

(569, 31)

In [52]:
data['diagnosis'].unique()

array(['M', 'B'], dtype=object)


### Benign = no cancer
### malignant = cancer

In [53]:
data['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [54]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [55]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size=0.2)

In [56]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [57]:
scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [58]:
x_train

array([[-0.08128347, -1.43186866, -0.09826226, ..., -0.22630328,
        -1.21425106, -0.64456604],
       [ 1.76377515,  0.65587776,  1.68605909, ...,  1.14017888,
         0.00819279, -1.41626565],
       [-0.54532683, -0.32631732, -0.57660027, ..., -0.31961665,
         0.89932008, -0.84305074],
       ...,
       [-0.66203234, -0.43338124, -0.69196414, ..., -0.37880571,
         0.32155623, -0.78133701],
       [ 1.72487331,  0.57208861,  1.64988226, ...,  0.9061405 ,
        -0.48143759, -0.93256344],
       [ 0.53836724, -0.75690048,  0.54447931, ...,  0.13003903,
         0.4064255 ,  0.30449106]])

In [59]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [60]:
x_train_tensor = torch.from_numpy(x_train.astype(np.float32))
x_test_tensor = torch.from_numpy(x_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [61]:
x_train_tensor

tensor([[-0.0813, -1.4319, -0.0983,  ..., -0.2263, -1.2143, -0.6446],
        [ 1.7638,  0.6559,  1.6861,  ...,  1.1402,  0.0082, -1.4163],
        [-0.5453, -0.3263, -0.5766,  ..., -0.3196,  0.8993, -0.8431],
        ...,
        [-0.6620, -0.4334, -0.6920,  ..., -0.3788,  0.3216, -0.7813],
        [ 1.7249,  0.5721,  1.6499,  ...,  0.9061, -0.4814, -0.9326],
        [ 0.5384, -0.7569,  0.5445,  ...,  0.1300,  0.4064,  0.3045]])

In [62]:
y_train_tensor.view(-1, 1)

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [63]:
y_train_tensor

tensor([0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
        1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
        0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 1., 0., 

In [64]:
y_train_tensor.reshape(-1, 1)

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [65]:
type(x_train_tensor)

torch.Tensor

In [66]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [67]:
data.shape

(569, 31)

In [68]:
x_train.shape

(455, 30)

In [74]:
learning_rate = 0.1
epochs = 100

In [75]:
loss_function = nn.BCELoss()

In [76]:
model = MySimpleNN(x_train.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [77]:
for epoch in range(epochs):
  y_pred = model(x_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # clear gradient
  optimizer.zero_grad()

  loss.backward()
  # parameters update
  optimizer.step()

  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6447117328643799
Epoch: 2, Loss: 0.6401110887527466
Epoch: 3, Loss: 0.6356026530265808
Epoch: 4, Loss: 0.63076251745224
Epoch: 5, Loss: 0.6257967352867126
Epoch: 6, Loss: 0.6205716729164124
Epoch: 7, Loss: 0.6151363253593445
Epoch: 8, Loss: 0.6094316840171814
Epoch: 9, Loss: 0.6034878492355347
Epoch: 10, Loss: 0.5973061323165894
Epoch: 11, Loss: 0.5908401608467102
Epoch: 12, Loss: 0.5841465592384338
Epoch: 13, Loss: 0.5772391557693481
Epoch: 14, Loss: 0.5702088475227356
Epoch: 15, Loss: 0.5630935430526733
Epoch: 16, Loss: 0.5559682250022888
Epoch: 17, Loss: 0.5487891435623169
Epoch: 18, Loss: 0.5415725708007812
Epoch: 19, Loss: 0.5343590974807739
Epoch: 20, Loss: 0.5272184610366821
Epoch: 21, Loss: 0.5201403498649597
Epoch: 22, Loss: 0.5131014585494995
Epoch: 23, Loss: 0.506170928478241
Epoch: 24, Loss: 0.4993932843208313
Epoch: 25, Loss: 0.49276816844940186
Epoch: 26, Loss: 0.4862977862358093
Epoch: 27, Loss: 0.4799751043319702
Epoch: 28, Loss: 0.47382333874702454
Ep

In [94]:
with torch.no_grad():
  y_pred = model(x_test_tensor)

  # y_pred_label = torch.where(y_pred > 0.5, 1, 0)
  y_pred_label = (y_pred > 0.5).float()
  accuracy = (y_pred_label == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5497075915336609


In [95]:
summary(model)

Layer (type:depth-idx)                   Param #
MySimpleNN                               --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       93
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 97
Trainable params: 97
Non-trainable params: 0

# Dataset and DataLoader

In [96]:
from sklearn.datasets import make_classification
import torch

In [97]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [99]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [100]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [109]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

<ipython-input-109-b05a7ba812dd>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
<ipython-input-109-b05a7ba812dd>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.long)


In [110]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [111]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [112]:
from torch.utils.data import Dataset, DataLoader

In [114]:
class CustomDataSet(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [115]:
dataset = CustomDataSet(X, y)

In [116]:
len(dataset)

10

In [117]:
dataset[1]

(tensor([-1.1402, -0.8388]), tensor(0))

In [119]:
dataset[7]

(tensor([1.7774, 1.5116]), tensor(1))

In [120]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [121]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)


tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


Assignment:
https://www.kaggle.com/datasets/abhi8923shriv/sentiment-analysis-dataset?select=test.csv