In [2]:
import torch

In [3]:
torch.__version__

'2.5.1+cu121'

In [4]:
! nvidia-smi

Mon Jan 27 11:13:21 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

Tesla T4
cuda


In [6]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
type(a)

torch.Tensor

In [8]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
torch.rand(3, 2)

tensor([[0.2820, 0.9341],
        [0.0778, 0.4551],
        [0.5410, 0.3899]])

In [12]:
torch.rand(3,2)

tensor([[0.5070, 0.8534],
        [0.9213, 0.4620],
        [0.2990, 0.4463]])

In [13]:
torch.manual_seed(123)
torch.rand(3,2)

tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])

In [14]:
torch.manual_seed(123)
torch.rand(3,2)

tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])

In [15]:
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [16]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [18]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [19]:
# Generate 20 numbers between 0 to 10
torch.linspace(0,10,20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [20]:
torch.linspace(0, 1, 30)

tensor([0.0000, 0.0345, 0.0690, 0.1034, 0.1379, 0.1724, 0.2069, 0.2414, 0.2759,
        0.3103, 0.3448, 0.3793, 0.4138, 0.4483, 0.4828, 0.5172, 0.5517, 0.5862,
        0.6207, 0.6552, 0.6897, 0.7241, 0.7586, 0.7931, 0.8276, 0.8621, 0.8966,
        0.9310, 0.9655, 1.0000])

In [21]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [23]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[3833231108317013296, 7454421801564381745, 2322206376936961119],
        [8387229111175570210, 2484135899465670501, 7958535038077902892]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])

In [29]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [31]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [32]:
x*3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [33]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [34]:
c = torch.tensor([1, -2, 3, -4])

In [35]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [38]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [40]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [42]:
torch.randint(size=(3, 4), low=0, high=10)

tensor([[6, 1, 2, 9],
        [4, 1, 3, 0],
        [0, 6, 5, 7]])

In [45]:
e = torch.randint(size=(3, 4), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 5., 2., 9.],
        [4., 0., 4., 8.],
        [1., 2., 6., 9.]])

In [46]:
torch.sum(e)

tensor(50.)

In [48]:
torch.sum(e, dim=0) # column wise sum

tensor([ 5.,  7., 12., 26.])

In [49]:
torch.sum(e, dim=1)

tensor([16., 16., 18.])

In [50]:
torch.mean(e, dim=1)

tensor([4.0000, 4.0000, 4.5000])

In [52]:
torch.mean(e)

tensor(4.1667)

In [53]:
torch.min(e)

tensor(0.)

In [57]:
torch.max(e)

tensor(9.)

In [58]:
# give a index of highest value
torch.argmax(e)

tensor(3)

In [59]:
# give a index of minimum value
torch.argmin(e)

tensor(0)

In [60]:
e

tensor([[0., 5., 2., 9.],
        [4., 0., 4., 8.],
        [1., 2., 6., 9.]])

In [61]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

In [62]:
f

tensor([[7, 5, 5],
        [6, 4, 4]])

In [63]:
g

tensor([[2, 9],
        [3, 8],
        [2, 6]])

In [64]:
torch.matmul(f,g)

tensor([[ 39, 133],
        [ 32, 110]])

In [65]:
h = torch.randint(size=(2,3), low=0, high=10)

In [66]:
f.shape, h.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [67]:
torch.matmul(f, h)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [68]:
torch.matmul(f, h.T)

tensor([[ 57, 104],
        [ 48,  86]])

In [69]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [70]:
vector1

tensor([1, 2])

In [71]:
vector2

tensor([3, 4])

In [72]:
torch.dot(vector1, vector2)

tensor(11)

In [73]:
torch.matmul(vector1, vector2)

tensor(11)

In [75]:
f

tensor([[7, 5, 5],
        [6, 4, 4]])

In [76]:
torch.transpose(f, 0, 1)

tensor([[7, 6],
        [5, 4],
        [5, 4]])

In [81]:
i = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [82]:
i

tensor([[0., 7., 8.],
        [6., 5., 1.],
        [9., 0., 3.]])

In [83]:
torch.inverse(i)

tensor([[-0.0355,  0.0496,  0.0780],
        [ 0.0213,  0.1702, -0.1135],
        [ 0.1064, -0.1489,  0.0993]])

In [84]:
torch.log(i)

tensor([[  -inf, 1.9459, 2.0794],
        [1.7918, 1.6094, 0.0000],
        [2.1972,   -inf, 1.0986]])

In [85]:
torch.exp(i)

tensor([[1.0000e+00, 1.0966e+03, 2.9810e+03],
        [4.0343e+02, 1.4841e+02, 2.7183e+00],
        [8.1031e+03, 1.0000e+00, 2.0086e+01]])

In [87]:
torch.softmax(i, dim=0)

tensor([[1.1754e-04, 8.8009e-01, 9.9241e-01],
        [4.7420e-02, 1.1911e-01, 9.0496e-04],
        [9.5246e-01, 8.0254e-04, 6.6868e-03]])